apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-1
spec:
  # how the volume should be mounted in the host
  accessModes:
    - ReadWriteOnce

  # storage size
  capacity:
    storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
