apiVersion: v1
kind: Pod
metadata:
  name: write-to-volume-pod
spec:
  containers:
    - name: alpine
      image: alpine
      command:
        - /bin/sh
        - -c
        - echo "test" > /mnt/volume/test.txt
      volumeMounts:
        - mountPath: /mnt/volume
          name: test-volume
  volumes:
    - name: test-volume
      emptyDir: {}
