apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    name: myapp
spec:
  containers:
    - name: simple-pod
      image: busybox
      args:
        # keep running for 1H
        - sleep
        - "3600"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
