apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-1
spec:
  # how the volume should be mounted in the host
  accessModes:
    - ReadWriteOnce

  # storage size
  capacity:
    storage: 100Mi

  hostPath:
    # a directory on the node where the pod will run
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    # This file claims the storage defined in the PersistentVolume.
    # The claim size must not exceed the size of the PV.
    #  The PVC will bind to the available PV if its specifications match the PVC requirements (like size and access modes)
    requests:
      storage: 99Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    name: myapp
spec:
  containers:
    - name: simple-pod
      image: busybox
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc-1
