apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end

spec:
  replicas: 3

  selector:
    # this matchLabels must be one of the labels in spec.template.metadata.labels
    matchLabels:
      type: front-end

  template:
    metadata:
      name: myapp-pod
      # labels for pod in the replicaSet
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
