kind: Deployment
apiVersion: apps/v1

metadata:
  name: myapp
  labels:
    app: myapp
    type: front-end

spec:
  replicas: 3

  selector:
    # this Deployment manages pods that have labels matching tpye: front-end
    matchLabels:
      type: front-end

  # describes the pod that will be created by the Deployment.
  template:
    metadata:
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        # name is the name of the container
        - name: nginx-container
          image: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"