kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-client-app
  template:
    metadata:
      labels:
        app: my-client-app
    spec:
      containers:
        - name: my-client
          image: ubuntu:latest
          imagePullPolicy: Never
          command: ["tail", "-f", "/dev/null"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"