kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  # map port from host machine to port on container
  labels:
    plane-type: data-plane
  extraPortMappings:
    - containerPort: 30080
      hostPort: 30080
      protocol: TCP
    - containerPort: 30081
      hostPort: 30081
      protocol: TCP
- role: worker
  labels:
    plane-type: data-plane