apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-1
spec:
  # how the volume should be mounted in the host
  accessModes:
    - ReadWriteOnce
  # storage size
  capacity:
    storage: 100Mi

  hostPath:
    # a directory on the node where the pod will run
    path: /mnt/data
---
apiVersion: v1
# The PVC will automatically bind to the available PV if PV's specifications match the PVC requirements (like size, access modes)
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # this PVC requests for at least 99 Mibibytes storage, the actual storage depends on the bound PV
      storage: 99Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    name: myapp
spec:
  containers:
    - name: pod-1
      image: busybox
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        # mounts the volume test-volume to the path /mnt/volume inside the container.
        - mountPath: /mnt/volume
          name: my-volume-1
  volumes:
    - name: my-volume-1
      persistentVolumeClaim:
        claimName: my-pvc-1
