apiVersion: v1
kind: Pod
metadata:
  name: write-to-volume-pod
spec:
  volumes:
    - name: test-volume
      hostPath:
        # directory location on host
        path: /var/log
  containers:
    - name: alpine
      image: alpine
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      command:
        - /bin/sh
        - -c
        - echo "test" > /mnt/volume/test.txt
      volumeMounts:
        # mounts the volume test-volume to the path /mnt/volume inside the container.
        - name: test-volume
          mountPath: /mnt/volume
