apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: myStorageClass
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
# volumeBindingMode controls when/how PV is bound to PVC
# - Immediate: default, the PV is provisioned and bound to the PVC as soon as the PVC is created
# - WaitForFirstConsumer: the binding/provisioning of PV is delayed until a Pod using the PVC is scheduled
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: storage.k8s.io/v1
# Defines mutable performance attributes that can be changed 
# on an already-provisioned volume without re-provisioning or data migration
kind: VolumeAttributesClass
metadata:
  name: myVolumeAttributesClass
driverName: ebs.csi.aws.com
parameters:
  iops: "16000"
  throughput: "1000"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myPVC1
spec:
  # dynamically provison PV by SC
  storageClassName: myStorageClass
  # use VolumeAttributesClass to set the volume attributes
  volumeAttributesClassName: myVolumeAttributesClass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    name: myapp
spec:
  volumes:
    - name: my-volume-1
      persistentVolumeClaim:
        claimName: myPVC1
    - name: my-volume-2
      # volumeClaimTemplate: reference to a PVC template to be used for the volume
      # the PVC will be created dynamically when the pod is created
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: myStorageClass
            volumeMode: Filesystem
  # mounts the volume my-volume to the path /tmp/log inside the container
  containers:
    - name: simple-pod
      image: busybox
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: "/tmp/log"
          name: my-volume-1
        - mountPath: "/tmp/log"
          name: my-volume-2

